[tool.poetry]
name = "spirit-island"
version = "0.1.0"
description = ""
authors = ["Nathan Jones <nathanj439@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0.1"
django-debug-toolbar = "^5.0.0"
django-cleanup = "^9.0.0"
Pillow = "^11.0.0"
django-ninja = "^1.0.0"
gunicorn = "^23.0.0"
python-dotenv = "^1.0.0"
"discord.py" = "^2.5.0"
requests = "^2.0.0"
# structlog uses calendar versioning,
# so using ^ is unnecessarily restrictive
structlog = ">= 25.1.0"
redis = "^4.2.0"
django-prometheus = "^2.2.0"
# TODO: remove this dependency once all installations are using Python 3.11,
# since 3.11 has asyncio.timeout in the standard library
# will need to first migrate bot.py to use the standard library
async-timeout = "^5.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
